package com.ds.transfer.record.mapper;

import com.ds.transfer.record.entity.ApiInfoEntity;
import com.ds.transfer.record.entity.ApiInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiInfoEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int countByExample(ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int deleteByExample(ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int insert(ApiInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int insertSelective(ApiInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	List<ApiInfoEntity> selectByExampleWithBLOBs(ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	List<ApiInfoEntity> selectByExample(ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	ApiInfoEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ApiInfoEntity record, @Param("example") ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ApiInfoEntity record, @Param("example") ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByExample(@Param("record") ApiInfoEntity record, @Param("example") ApiInfoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByPrimaryKeySelective(ApiInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ApiInfoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table api_info
	 * @mbggenerated  Sun Jul 03 13:59:58 CST 2016
	 */
	int updateByPrimaryKey(ApiInfoEntity record);
}